package com.util.enums;

public enum Deficiencia {

	CEGUEIRA, 
	BAIXA_VISAO, 
	SURDEZ, 
	DEFICIENCIA_AUDITIVA, 
	SURDOCEGUEIRA, 
	DEFICIENCIA_FISICA, 
	DEFICIENCIA_INTELECTUAL, 
	DEFICIENCIA_MULTIPLA, 
	AUTISMO, 
	SINDROME_DE_RETT, 
	SINDROME_DE_ASPERGER, 
	TRANSTORNO_DA_INFANCIA, 
	ALTAS_HABILIDADES;

}
